// GENERATED by `pnpm season:images`. Do not edit.
// SPEC-FINAL 16.7: the database stores only the path string; this list is what
// makes the server able to refuse a season whose image is not committed.
export const SEASON_IMAGE_MANIFEST = [
  'seasons/2026/field.webp',
] as const;

export type SeasonImagePath = (typeof SEASON_IMAGE_MANIFEST)[number];
