#!/usr/bin/env node
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SEASONS_DIR = join(ROOT, 'apps/client/public/seasons');
const TARGET = join(ROOT, 'packages/shared/src/season/manifest.ts');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

function render() {
  let files = [];
  try {
    files = walk(SEASONS_DIR)
      .filter((f) => f.endsWith('.webp'))
      .map((f) => relative(join(ROOT, 'apps/client/public'), f).split('\\').join('/'))
      .sort();
  } catch {
    files = [];
  }
  const entries = files.map((f) => `  '${f}',`).join('\n');
  return [
    '// GENERATED by `pnpm season:images`. Do not edit.',
    '// SPEC-FINAL 16.7: the database stores only the path string; this list is what',
    '// makes the server able to refuse a season whose image is not committed.',
    `export const SEASON_IMAGE_MANIFEST = [\n${entries}\n] as const;`,
    '',
    'export type SeasonImagePath = (typeof SEASON_IMAGE_MANIFEST)[number];',
    '',
  ].join('\n');
}

const rendered = render();
if (process.argv.includes('--check')) {
  const current = readFileSync(TARGET, 'utf8');
  if (current !== rendered) {
    console.error('drift: packages/shared/src/season/manifest.ts is stale.');
    console.error('Run `pnpm season:images` and commit the result.');
    process.exit(1);
  }
} else {
  writeFileSync(TARGET, rendered, 'utf8');
  console.warn(`wrote ${TARGET}`);
}
